// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates collaboration suggestions based on user input.
 *
 * - generateCollaborationSuggestions - A function that generates collaboration suggestions.
 * - CollaborationSuggestionsInput - The input type for the generateCollaborationSuggestions function.
 * - CollaborationSuggestionsOutput - The return type for the generateCollaborationSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CollaborationSuggestionsInputSchema = z.object({
  projectRequirements: z
    .string()
    .describe('Detailed description of the project requirements.'),
  collaborationPreferences: z
    .string()
    .describe('Any specific collaboration preferences the user has.'),
});
export type CollaborationSuggestionsInput = z.infer<
  typeof CollaborationSuggestionsInputSchema
>;

const CollaborationSuggestionsOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('A list of suggested collaboration models.'),
});
export type CollaborationSuggestionsOutput = z.infer<
  typeof CollaborationSuggestionsOutputSchema
>;

export async function generateCollaborationSuggestions(
  input: CollaborationSuggestionsInput
): Promise<CollaborationSuggestionsOutput> {
  return generateCollaborationSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'collaborationSuggestionsPrompt',
  input: {schema: CollaborationSuggestionsInputSchema},
  output: {schema: CollaborationSuggestionsOutputSchema},
  prompt: `You are an AI assistant specializing in suggesting collaboration models for web design projects. Analyze the user's project requirements and collaboration preferences to suggest optimal partnership options.

Project Requirements: {{{projectRequirements}}}
Collaboration Preferences: {{{collaborationPreferences}}}

Consider options like 'free site for 20% of revenues' or 'price per lead'. Tailor the advice based on the project's scope and the user's specific requirements. Provide suggestions that are creative and mutually beneficial.

Output the suggestions as a numbered list.
`,
});

const generateCollaborationSuggestionsFlow = ai.defineFlow(
  {
    name: 'generateCollaborationSuggestionsFlow',
    inputSchema: CollaborationSuggestionsInputSchema,
    outputSchema: CollaborationSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
