import type { Metadata } from 'next';

// src/app/terms-of-service/page.tsx
export const metadata: Metadata = {
  title: 'Terms of Service | Webara Studio',
  description:
    'Review the Webara Studio Terms of Service covering use of our website, AI-generated quotes, and project engagements.',
  alternates: {
    canonical: 'https://webarastudio.com/terms-of-service',
  },
};

import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function TermsOfServicePage() {
  return (
    <div className="flex min-h-dvh flex-col bg-background">
      <Header />
      <main className="flex-1 py-12 sm:py-16 md:py-20">
        <div className="container mx-auto max-w-4xl px-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-3xl font-bold tracking-tight">Terms of Service</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6 text-foreground/80">
              <p>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
                <p>
                  By accessing and using this website, you accept and agree to be bound by the terms and provision of this
                  agreement. If you do not agree to abide by the above, please do not use this service.
                </p>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold">2. AI-Generated Content</h2>
                <p>
                  The quotes and suggestions provided on this website are generated by an artificial intelligence model. They are
                  for informational and preliminary purposes only and do not constitute a binding offer. A formal proposal
                  will be provided after consultation with our team.
                </p>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold">3. User Conduct</h2>
                <p>
                  You agree not to use the website for any unlawful purpose or any purpose prohibited under this clause. You
                  agree not to use the website in any way that could damage the website, the services, or the general business of
                  Webara Studio.
                </p>
              </div>
              
              <div className="space-y-4">
                <h2 className="text-xl font-semibold">4. Limitation of Liability</h2>
                <p>
                  Webara Studio is not liable for any damages that may occur to you as a result of your use of the website, to
                  the fullest extent permitted by law.
                </p>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold">5. Changes to Terms</h2>
                <p>
                  We reserve the right to change these terms and conditions at any time. We will do our best to notify users of
                  any changes, but it is your responsibility to check for updates.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  );
}
